### ISSUE TITLE
Is it necessary to query account balance at any block number? 

### ISSUE THREAD

**Issue by Pana** [coinbase/rosetta-specifications#88] opened 2021-12-21 06:24 UTC
Conflux is a high-performance public chain, we are working on integrating with Rosetta. But we have encountered a problem that is Our chain default won’t save all historical states, which means only supporting query account balance in the latest blocks for example latest 5w blocks.

If one want query balance in any block height, the fullnode’s disk storage will be very very big maybe several hundred T

So if it is Ok for the query balance Data-API only support query balance at latest 5w blocks ?

**Comment by shrimalmadhur** [comment] 2021-12-23 19:44
I think this is a duplicate of https://community.rosetta-api.org/t/is-it-necessary-to-query-account-balance-at-any-block-number/651 - so closing this and we can discuss more there. Thanks

**Closed by shrimalmadhur** 2021-12-23 19:44 UTC
Labels: enhancement
